update=11-Mar-18 6:15:38 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=../KCAD_libs
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Audio
LibName31=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Buffer
LibName32=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Current
LibName33=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Difference
LibName34=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Instrumentation
LibName35=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Operational
LibName36=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Amplifier_Video
LibName37=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Analog
LibName38=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Analog_ADC
LibName39=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Analog_DAC
LibName40=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Analog_Switch
LibName41=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Audio
LibName42=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Battery_Management
LibName43=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Comparator
LibName44=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Connector_Generic
LibName45=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Connector_Generic_Shielded
LibName46=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Connector_Specialized
LibName47=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Converter_DCDC
LibName48=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/CPLD_Altera
LibName49=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/CPLD_Xilinx
LibName50=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/CPU
LibName51=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Device
LibName52=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Diode
LibName53=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Diode_Bridge
LibName54=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Diode_Laser
LibName55=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Display_Character
LibName56=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Display_Graphic
LibName57=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Driver_Display
LibName58=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Driver_FET
LibName59=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Driver_LED
LibName60=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Driver_Motor
LibName61=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Driver_Relay
LibName62=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/DSP_Freescale
LibName63=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/DSP_Microchip_DSPIC33
LibName64=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/DSP_Texas
LibName65=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Actel
LibName66=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx
LibName67=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx_Artix7
LibName68=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx_Kintex7
LibName69=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx_Spartan6
LibName70=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx_Virtex5
LibName71=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx_Virtex6
LibName72=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/FPGA_Xilinx_Virtex7
LibName73=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Graphic
LibName74=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface
LibName75=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_CAN_LIN
LibName76=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_CurrentLoop
LibName77=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_Ethernet
LibName78=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_Expansion
LibName79=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_HID
LibName80=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_LineDriver
LibName81=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_Optical
LibName82=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_Telecom
LibName83=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_UART
LibName84=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Interface_USB
LibName85=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Isolator
LibName86=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Isolator_Analog
LibName87=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Jumper
LibName88=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/LED
LibName89=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_74xgxx
LibName90=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_74xx
LibName91=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_CMOS_4000
LibName92=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_CMOS_IEEE
LibName93=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_LevelTranslator
LibName94=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_Programmable
LibName95=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Logic_TTL_IEEE
LibName96=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_AnalogDevices
LibName97=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Atmel_8051
LibName98=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Atmel_ATMEGA
LibName99=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Atmel_ATTINY
LibName100=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Atmel_AVR
LibName101=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Cypress
LibName102=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Infineon
LibName103=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Intel
LibName104=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_PIC10
LibName105=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_PIC12
LibName106=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_PIC16
LibName107=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_PIC18
LibName108=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_PIC24
LibName109=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_PIC32
LibName110=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_SAME
LibName111=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Microchip_SAML
LibName112=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Module
LibName113=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_NXP_HC11
LibName114=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_NXP_Kinetis
LibName115=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_NXP_LPC
LibName116=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_NXP_S08
LibName117=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Parallax
LibName118=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_SiFive
LibName119=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_SiliconLabs
LibName120=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_ST_STM8
LibName121=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_ST_STM32
LibName122=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Texas
LibName123=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/MCU_Texas_MSP430
LibName124=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Mechanical
LibName125=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_Controller
LibName126=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_EEPROM
LibName127=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_Flash
LibName128=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_NVRAM
LibName129=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_RAM
LibName130=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_ROM
LibName131=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Memory_UniqueID
LibName132=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Motor
LibName133=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Oscillator
LibName134=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Potentiometer_Digital
LibName135=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/power
LibName136=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Power_Management
LibName137=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Power_Protection
LibName138=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Power_Supervisor
LibName139=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/pspice
LibName140=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Reference_Current
LibName141=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Reference_Voltage
LibName142=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Regulator_Controller
LibName143=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Regulator_Current
LibName144=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Regulator_Linear
LibName145=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Regulator_SwitchedCapacitor
LibName146=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Regulator_Switching
LibName147=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Relay
LibName148=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Relay_SolidState
LibName149=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF
LibName150=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_AM_FM
LibName151=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_Bluetooth
LibName152=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_GPS
LibName153=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_Mixer
LibName154=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_Module
LibName155=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_RFID
LibName156=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_WiFi
LibName157=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/RF_ZigBee
LibName158=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor
LibName159=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Audio
LibName160=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Current
LibName161=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Gas
LibName162=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Humidity
LibName163=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Magnetic
LibName164=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Motion
LibName165=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_MultiFunction
LibName166=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Optical
LibName167=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Pressure
LibName168=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Proximity
LibName169=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Temperature
LibName170=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Touch
LibName171=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Sensor_Voltage
LibName172=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Switch
LibName173=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Timer
LibName174=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Timer_RTC
LibName175=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Transformer
LibName176=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Transistor_Array
LibName177=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Transistor_BJT
LibName178=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Transistor_FET
LibName179=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Transistor_IGBT
LibName180=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Triac_Thyristor
LibName181=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Valve
LibName182=C:/Program Files/KiCad/share/kicad/library/kicad-symbols-master/Video
LibName183=D:/my_projects/electro/KCAD_libs/Driver_stepper_ST
LibName184=Driver_stepper_ST
[general]
version=1
